### ISSUE TITLE
status transaction

### ISSUE THREAD

**Issue by 061275sergey** [zkSync-Community-Hub/zkync-developers#114]
i can't get my funds
0xb655d4fe85ff654c440b90726b494ee8b1f4845ff2dfbb196203197685ef4672

**Comment by 0xsisyfos** [comment]
The funds have been transferred:
https://explorer.zksync.io/tx/0xb655d4fe85ff654c440b90726b494ee8b1f4845ff2dfbb196203197685ef4672

You can read more on the transactions statuses in our docs:
https://era.zksync.io/docs/reference/concepts/transactions.html#transaction-statuses
