### ISSUE TITLE
Deposite Zksync Lite Token Not Recived

### ISSUE THREAD

**Issue by souviksingha123** [zkSync-Community-Hub/zkync-developers#177]
I use this site https://lite.zksync.io/account/history and Transfer my Zksync Lite Token 
0.001996990986 ETH to 
Binance ETH Deposit Address = 0x5056c19839093b1c7930e15eedccdaf62b7eb3b8
And Then Transfer Complete  But Not Recive My Zksync Eth In Binance. 

Tx Hash = 0x347c45f314499ecca27445981690bebcc35990d803c1834c43b2d5960cded1d3

Why This Happen.

**Comment by MexicanAce** [comment]
This transaction was completed and can be seen here: https://zkscan.io/explorer/transactions/0x347c45f314499ecca27445981690bebcc35990d803c1834c43b2d5960cded1d3

The funds in question were transferred to the Address on zkSync Lite as you described: 0x5056c19839093b1c7930e15eedccdaf62b7eb3b8

> [...] Not Recive My Zksync Eth In Binance
Unfortunately, we have no way to validate that the address the token was sent to has any relation to Binance. The funds are on zkSync Lite and not Layer 1.
