### ISSUE TITLE
zksync to eth mainnet transfer issue

### ISSUE THREAD

**Issue by sektrade** [zkSync-Community-Hub/zkync-developers#33]
Although the eth I transferred from the zksync network to the eth mainnet network at https://lite.zksync.io/transaction/withdraw shows successful in etherscan, it does not appear in the wallet. I contacted MM and was told that the problem is from the target chain. Anyone find a solution for this?

**Comment by bxpana** [comment]
If you're still having issues, please email us at support@zksync.io and we can help you there.
