### ISSUE TITLE
Please BEWARE: Got  scammed by the below link. Was trying to bridge my ETH to ZKSYNC.   

### ISSUE THREAD

**Issue by Garbs4real** [zkSync-Community-Hub/zkync-developers#61]
zkSync Era Bridge | Transfer funds between zkSync Era ...

zkera-brldge.cloud
https://www.zkera-brldge.cloud
Your bridge to the future of crypto and DeFi powered with zero knowledge proofs. MetaMask. Connect using browser wallet. 1.13.0.
You visited this page on 11/07/23.

Here is the transaction Hash:  0x30b68119e0e8fa1ee64bcf0f086c8343bd28d5165d147ce0c7df1be0fd2c594f

Here 👍 is my REQUEST to PLEASE return my ETH... Its all i have.

" Why are you so evil ?... stealing innocent people money, KARMA will fall or you . Remember all is nothing . Year's from now, you will be in shackles  ... Return my ETH ( Hard earn work, my hope of helping other from my home country (AFRICA) was
taken by you)
Transaction ID: 0x30b68119e0e8fa1ee64bcf0f086c8343bd28d5165d147ce0c7df1be0fd2c594f

My Address: 0x40242De312f4f9B8CE28BEAbffE9dB6549Dfd8b2 Thank's and will appreciate if you have a rethink.....

**Comment by HenryEnrique** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by Garbs4real** [comment]
Thanks , Have sent him a message, hope he cloud help!.
________________________________

**Comment by tolkel** [comment]
All these scammers sef

**Comment by bxpana** [comment]
@Garbs4real I'm truly sorry to hear about your unfortunate experience.

Unfortunately, with scams of this nature, there's nothing that can be done. To avoid such incidents in the future, always use our official webpage, https://zksync.io/, for bridging and any other activities. This ensures that you're accessing authentic and safe links.

Additionally, please be wary of unsolicited contacts offering to direct you to 'helpers' or 'support staff'. This is often a tactic used by scammers to extract even more from their victims. Our community on Discord (https://join.zksync.dev/) is an excellent resource. You can pose questions about any links or offers you find suspicious, and our active members often share their experiences and issue warnings about emerging scams.

Once again, I'm genuinely sorry for the distress this has caused you. Please stay cautious and always consult trusted sources or our community when in doubt.

**Comment by bxpana** [comment]
@Garbs4real I'm truly sorry to hear about your unfortunate experience.

Unfortunately, with scams of this nature, there's nothing that can be done. To avoid such incidents in the future, always use our official webpage, https://zksync.io/, for bridging and any other activities. This ensures that you're accessing authentic and safe links.

Additionally, please be wary of unsolicited contacts offering to direct you to 'helpers' or 'support staff'. This is often a tactic used by scammers to extract even more from their victims. Our community on Discord (https://join.zksync.dev/) is an excellent resource. You can pose questions about any links or offers you find suspicious, and our active members often share their experiences and issue warnings about emerging scams.

Once again, I'm genuinely sorry for the distress this has caused you. Please stay cautious and always consult trusted sources or our community when in doubt.
